### ISSUE TITLE
When we hover over the header navigation then the some of the categories the main images are missing in most of all the categories.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#1]
**Actual result:** 
When we hover over the header navigation then the some of the categories the main images are missing in most of all the categories.
The video issue: https://www.awesomescreenshot.com/video/8613175?key=542534441b46de959d0fc7ed4ffaaa33 
![image](https://user-images.githubusercontent.com/102131636/165437824-a70d08b9-b59c-4d4c-92f4-84d8db8d89ed.png)

**Expected result:** 
When we hover over the header navigation then the main image have to be visible properly.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  working on it, client had share the list of products related collection, once it done, will update in   group

**Comment by Shweta-PC** [comment]
@sudhanshu0603  This is not an issue. Once client will add the products for respective sub category the images will reflect.

**Comment by sudhanshu0603** [comment]
@dev-adityapatel , some of the collection do not have the images and some collection is having the same image.
![image](https://user-images.githubusercontent.com/102131636/166195536-72bf392c-52f1-4af3-966f-172f39db71df.png)

**Comment by sudhanshu0603** [comment]
ok, @Shweta-PC .
