### ISSUE TITLE
Account page after successfull login the phone number should not have validation for 10 digit exactly, some countries are having less or greater than 10 digit number.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#10]
**Actual result:** 
Account page after successfull login the phone number should not have validation for 10 digit exactly, some countries are having less or greater than 10 digit number.
![image](https://user-images.githubusercontent.com/102131636/165448273-500fafff-7d0c-4c8e-8c81-6b6c1793a3c3.png)

**Expected result:** 
The phone number should not have the validation for 10 digit some countries have less or greater than 10 digits.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  working fine, we follow validation accordion as in their store  
![image](https://user-images.githubusercontent.com/100192519/165954253-9200d428-143a-479d-82ac-cbe858206302.png)
If client will have  specific requirement then we will do it

**Comment by sudhanshu0603** [comment]
ok, resolved
