### ISSUE TITLE
When clicking on the social media icons on the footer then the 404 error page is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#12]
**Actual result:** 
When clicking on the social media icons on the footer then the 404 error page is coming.
![image](https://user-images.githubusercontent.com/102131636/165450246-5002cbfc-dc98-45e4-b4c0-96e9980e4867.png)
![image](https://user-images.githubusercontent.com/102131636/165450275-72bf0d50-c81a-4bcf-9213-857de569a1c8.png)

**Expected result:** 
When we click on the footer social media icons then the page related to it, have to be open.

--------------------------------------------------------------------------------------------------------------------------------------
**Restesting:** 
**Actual result:** 
When we click on the social media icons then it is opening the shopify platform.
![image](https://user-images.githubusercontent.com/102131636/165884780-93279bdd-9d27-4fbd-ba34-179d9ffa3407.png)

**Expected result:** 
When we click on the social media icon then it should open the social media platform.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  for now client have no social media account, it is dummy account, 404 error resolved

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  it is demo just, when client will share social media then  it will updated, also shared video to add social icon

**Comment by sudhanshu0603** [comment]
@Shweta-PC , please confirm this point

**Comment by Shweta-PC** [comment]
@sudhanshu0603  Currently client does not have social media page. It is under designing. So we will share the video with client on how to add and it will be done on the later basis by client.
