### ISSUE TITLE
Terms of services the contact details are missing on the section-20 point in the footer section.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#16]
**The url:** https://betterbuysales.com/pages/terms-of-service

**Actual result:** 
Terms of services the contact details are missing on the section-20 point in the footer section.
![image](https://user-images.githubusercontent.com/102131636/165454536-773cc8cd-3b02-4c36-831e-b9a1c4b0e0df.png)

**Expected result:** 
The contact details have to be added .

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/165724419-d5cd0c37-0421-4eef-b934-6ec8e02abe84.png)
@sudhanshu0603  Done

**Comment by sudhanshu0603** [comment]
ok, resolved
