### ISSUE TITLE
The returns and refund policy speeling is not correct and the page title needs to be updated.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#17]
**Actual result:** 
1: The spelling in the footer should be Returns and Refund Policy it is coming in singular.
![image](https://user-images.githubusercontent.com/102131636/165455237-12b9d038-80c3-4585-9622-10fa8783f85e.png)
2: When we click on it then only the title is coming Refund Policy.
![image](https://user-images.githubusercontent.com/102131636/165455338-882cba45-7d38-43c6-acd5-800776c97911.png)

**Expected result:**
The speeling and the title have to be updated

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/165722241-1e1ca081-c0af-47cd-8099-86694b67df91.png)
@sudhanshu0603  Done

**Comment by sudhanshu0603** [comment]
ok, resolved
