### ISSUE TITLE
The banners are not clickable in the home page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#18]
**Actual result:** 
The banners are not clickable in the home page.
![image](https://user-images.githubusercontent.com/102131636/165456966-31775d9e-2820-4019-a5aa-5de654ff1238.png)
![image](https://user-images.githubusercontent.com/102131636/165456998-fe794fa5-6c65-4122-b9ef-422f3cac9473.png)

**Expected result:** 
Banners have to be clickable, and open the page related to it.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resloved

**Comment by sudhanshu0603** [comment]
ok, resolved
