### ISSUE TITLE
When we don't have a product on the collection then we can remove the unwanted filter. We can add continue shopping link and it should open the all product page or the homepage.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#2]
**Actual result:** 
When we don't have a product on the collection then we can remove the unwanted filter. We can add continue shopping link and it should open the all product page or the homepage.
![image](https://user-images.githubusercontent.com/102131636/165439043-1bfde2ea-9c11-45fd-be1b-4f62fb9f87b7.png)

**Expected result:** 
The reference is attached below,.
![image](https://user-images.githubusercontent.com/102131636/165439162-ef59bdea-06bf-4f76-be54-fef53ae15c6e.png)
-------------------------------------------------------------------------------------------------------------------------------------
**Retesting:** 
**Actual result:** 
The continue shopping link is looking like text. but it is a link.
![image](https://user-images.githubusercontent.com/102131636/165886216-cccf6b78-73e7-4395-96a7-d681d95e2769.png)
**Expected result:** 
If we use use css for continue shopping link it will be much better.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/165741762-18e87720-6d88-4cd6-9095-b3662dd6984b.png)

@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
