### ISSUE TITLE
The review comment need to be removed.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#21]
The url: https://betterbuysales.com/products/sutra-dryer-airpro-purple

**Actual result:** 
The review comment need to be removed.
![image](https://user-images.githubusercontent.com/102131636/165460746-3e93b06d-a9aa-4b39-adad-174c310bcd82.png)

**Expected result:** 
The review have to deleted it is not looking good.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  done

**Comment by sudhanshu0603** [comment]
ok, resolved
