### ISSUE TITLE
In Product page, the wishlist button and buy it now button is missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#23]
**Actual result:** 
In Product page, the wishlist button and buy it now button is missing.
![image](https://user-images.githubusercontent.com/102131636/165462552-5bedfb7c-53e7-47aa-bd25-b69804a72cdd.png)

**Expected result:** 
The  wishlist and buy it now buttons are not added in product page.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/165703945-875f3c88-e522-4045-b3fc-06d9b3a32e1a.png)
@sudhanshu0603  comin in stock products

**Comment by sudhanshu0603** [comment]
ok, resolved
