### ISSUE TITLE
In cart page, the size of the button for checkout and paypal are of different size.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#24]
**Actual result:** 
In cart page, the size of the button for checkout and paypal are of different size.
![image](https://user-images.githubusercontent.com/102131636/165467328-8164a4bc-18c0-4c5d-b993-18b247a03ff7.png)

**Expected result:** 
The size of the buttons have to be same it will be much better.

**Comment by ui-rishavkumar** [comment]
as discussed with arvind sir we don't need to change the size of the buttons

**Comment by sudhanshu0603** [comment]
ok, resolved
