### ISSUE TITLE
In wishlist page, when we are adding the product then it is not adding in the cart icon the count is not increasing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#29]
**Actual result:** 
In wishlist page, when we are adding the product then it is not adding in the cart icon the count is not increasing.
![image](https://user-images.githubusercontent.com/102131636/165491274-b4251280-75e7-4d68-b6f1-f8f894001cfe.png)

**Expected result:**
The count have to be increase when we are adding the wishlist product to the cart.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603   only in stock product will add to cart

**Comment by sudhanshu0603** [comment]
ok ,resolved
