### ISSUE TITLE
When we use the option of filters sortby then when we hover over the products then the wishlist icon will not be visible.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#3]
**Actual result:** 
When we use the option of filters sortby then when we hover over the products then the wishlist icon will not be visible.
![image](https://user-images.githubusercontent.com/102131636/165439738-c4e69be3-9196-4d29-96ad-02fb9d38126c.png)

**Expected result:** 
After using the filter the wishlist have to be visible.
![image](https://user-images.githubusercontent.com/102131636/165439851-701222de-f802-4e2d-8dfa-938e50ce87ed.png)

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
