### ISSUE TITLE
Are u sure section can be improved more after successfull login when we add product in the wishlist.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#30]
**Actual result:** 
Are u sure section can be improved more after successfull login when we add product in the wishlist.
![image](https://user-images.githubusercontent.com/102131636/165491866-17810ca5-f8de-4841-a635-0f396226dc3e.png)

**Expected result:** 
The are u sure section can be improved more.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  this section coming from apps, we can not customised it more

**Comment by sudhanshu0603** [comment]
ok, resolved
