### ISSUE TITLE
In cart page, the double price is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#32]
**Actual result:** 
In cart page, the double price is coming, we can change the color of both price it will be much better, and font size of pricing have to be of standard size.
![image](https://user-images.githubusercontent.com/102131636/165510245-407c53e0-7770-4cba-b143-ff20c69b345e.png)

**Expected result:** 
The pricing have to be of different color combination it will be much better.

**Comment by ui-rishavkumar** [comment]
font size was inc. and color remains same

**Comment by sudhanshu0603** [comment]
ok, resolved
