### ISSUE TITLE
In footer section, the policy speeling is coming in lowecase it has to be in capitalise form for the speeling Policy.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#34]
**Actual result:** 
In footer section, the policy speeling is coming in lowecase it has to be in capitalise form for the speeling Policy.
![image](https://user-images.githubusercontent.com/102131636/165512315-a0827945-173d-409c-9a9e-9651c8d6400f.png)

**Expected result:** 
The speeling of the Policy have to come in Uppercase.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  done

**Comment by sudhanshu0603** [comment]
ok, resolved
