### ISSUE TITLE
Some of the images are coming blur.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#40]
https://betterbuysales.com/collections/radio
**Actual result:** 
Some of the images are coming blur.
![image](https://user-images.githubusercontent.com/102131636/165521064-88c12998-6547-486d-b144-62cc317eb66d.png)

**Expected result:** 
The images have to be of good quality.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/165694669-4bbc3b74-65af-41c5-90f3-f5215a3c97c6.png)
@sudhanshu0603  Picture quality poor
