### ISSUE TITLE
shipping policy page in cart page content is missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#42]
**The url:**  https://betterbuysales.com/policies/shipping-policy

**Actual result:**
shipping policy page in cart page content is missing.

![image](https://user-images.githubusercontent.com/102131636/165675906-cb997f3f-80c5-4852-94a6-a028b8f0664d.png)

**Expected result:**
The content have to be added in the shipping page.
-----------------------------------------------------------------------------------------------------------------------------------

**Retesting:** 
**Actual result:** 
The content needs to be in single line, it is coming in multiple line.
![image](https://user-images.githubusercontent.com/102131636/165702394-f034b001-caa9-4b95-a3a4-b70334a6d5c0.png)

**Expected result:** 
The content needs to be in capitalise form and in a single line.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
