### ISSUE TITLE
In cart page, the image of the product have to be clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#43]
**Actual result:** 
In cart page, the image of the product have to be clickable.
![image](https://user-images.githubusercontent.com/102131636/165676746-af606084-7f73-49eb-b586-dcf91d452ad1.png)

**Expected result:** 
When we click on the main image on the cart page of the product added, it should open the page related to it.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
