### ISSUE TITLE
Inside the quick view, when we add to cart product then the success message is coming and when we increase the quantity or change the option then the success message have to be change.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#45]
**Actual result:**
Inside the quick view, when we add to cart product then the success message is coming and when we increase the quantity or change the option then the success message have to be change.
![image](https://user-images.githubusercontent.com/102131636/165678615-d026661e-191f-4a93-8a81-cb97db7e910f.png)

**Expected result:** 
The success message have to be disappears after some seconds it will be much better.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
