### ISSUE TITLE
When we clicking in this banner then it is opening the product page,

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#48]
**Actual result:** 
When we clicking in this banner then it is opening the product page,
![image](https://user-images.githubusercontent.com/102131636/165718136-75c73134-e71b-4dff-9d68-27d7a19320c4.png)

**Expected result:** 
It should opens the page related to it, when we click on this banner.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
