### ISSUE TITLE
For the search page, the dropdown is not coming for changing the filter option.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-wholesale---Internal--May-4th#49]
**Actual result:** 
1: For the search page, the dropdown is not coming for changing the filter option.
2: The product of the trimmers are many and count of search is showing the 10 products only.
![image](https://user-images.githubusercontent.com/102131636/165885584-eaa9a126-c6b8-43cc-a77f-51ea47bf912f.png)

**Expected result:** 
The dropdown is not coming in search page.
The count of the product in the search page have to be as number of products .

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue reolved

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/166101613-3b8fb4fe-bf68-4cd1-af32-a1706ba5aa65.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
